name: "core_result"

version: "1.0.0"

resolution: workspace

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  freezed_annotation: "3.1.0"

dev_dependencies:
  # Версии должны быть указаны точно, без диапазонов
  build_runner: "2.12.2"
  freezed: "3.2.5"

environment:
  sdk: "3.11.1"

publish_to: "none"
