name: "core_l10n"

version: "1.0.0"

resolution: workspace

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  flutter:
    sdk: "flutter"
  intl: "0.20.2"

dev_dependencies:
  # Версии должны быть указаны точно, без диапазонов
  intl_utils: "2.8.14"

flutter_intl:
  enabled: true
  main_locale: ru
  arb_dir: lib/l10n
  output_dir: lib/generated

environment:
  sdk: "3.11.1"
  flutter: "3.41.4"

publish_to: "none"
