name: "feature_home_screen"

version: "1.0.0"

resolution: workspace

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  bloc: "9.2.0"
  core_bloc: any
  core_chain: any
  core_dio: any
  core_failure: any
  core_result: any
  flutter:
    sdk: "flutter"
  flutter_bloc: "9.1.1"
  fluttertoast: "9.0.0"
  freezed_annotation: "3.1.0"
  go_router: "17.1.0"
  json_annotation: "4.11.0"

dev_dependencies:
  # Версии должны быть указаны точно, без диапазонов
  build_runner: "2.12.2"
  freezed: "3.2.5"
  json_serializable: "6.13.0"

environment:
  sdk: "3.11.1"
  flutter: "3.41.4"

publish_to: "none"
