name: "core_navigation"

version: "1.0.0"

resolution: workspace

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  core_platform: any
  flutter:
    sdk: "flutter"
  go_router: "17.1.0"

environment:
  sdk: "3.11.1"
  flutter: "3.41.4"

publish_to: "none"
